# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fakirbaba_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fakirbaba_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fakirbaba_production
  pool: 5
  username: sai
  password: admin